server:
  port: 9001



eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    username: sa
    password:
    url: jdbc:h2:~/test

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true